(defun mygetline (buf line)
  (setq oldBuffer (buffer-name))
  (switch-to-buffer buf)
  (goto-char 1)
  (forward-line line)
  (setq pos1 (point))
  (end-of-line)
  (setq pos2 (point))
  (setq str (buffer-substring pos1 pos2))
  (switch-to-buffer oldBuffer)
  (setq str str))

(defun mygetdata (buf line col)
  (setq dataList (split-string (mygetline buf line)))
  (setq res (nth col dataList)))

(defun mygoto (buf line col)
  (setq oldBuffer (buffer-name))
  (pop-to-buffer buf)
  (goto-char 1)
  (forward-line line)
  (forward-word col)
  (pop-to-buffer oldBuffer))
