(defun myf1 (str1 str2)
  (interactive "s\ns")
  (message str1)
  (message str2))

(defun mycinsert2 (str snum)
  (interactive "sInsert String:\nsNumber:")
  (setq num (string-to-number snum))
  (while (> num 0)
    (setq pos (point))
    (insert str)
    (goto-char pos)
    (next-line)
    (setq num (- num 1))))

(defun mycinsert (str)
  (interactive "sInsrt String:")
  (setq pos1 (region-beginning))
  (setq pos2 (region-end))
  (goto-char pos1)
  (setq line1 (line-number-at-pos))
  (goto-char pos2)
  (setq line2 (line-number-at-pos))
  (setq lnum (- line2 line1))
  (goto-char pos1)
  (while (>= lnum 0)
    (setq pos (point))
    (insert str)
    (goto-char pos)
    (next-line)
    (setq lnum (- lnum 1))))
  

(defun mycdel ()
  (interactive)
  (setq pos1 (region-beginning))
  (setq pos2 (region-end))
  (goto-char pos1)
  (setq line1 (line-number-at-pos))
  (setq col1 (current-column))
  (goto-char pos2)
  (setq line2 (line-number-at-pos))
  (setq col2 (current-column))
  (setq lnum (- line2 line1))
  (setq cnum (- col2 col1))
  (goto-char pos1)
  (while (>= lnum 0)
    (delete-char cnum)
    (next-line)
    (setq lnum (- lnum 1))))
    
  


